/*
  Copyright 2011-2014 Red Hat

  This file is part of PresGang CCMS.

  PresGang CCMS is free software: you can redistribute it and/or modify
  it under the terms of the GNU Lesser General Public License as published by
  the Free Software Foundation, either version 3 of the License, or
  (at your option) any later version.

  PresGang CCMS is distributed in the hope that it will be useful,
  but WITHOUT ANY WARRANTY; without even the implied warranty of
  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
  GNU Lesser General Public License for more details.

  You should have received a copy of the GNU Lesser General Public License
  along with PresGang CCMS.  If not, see <http://www.gnu.org/licenses/>.
*/

package org.jboss.pressgang.ccms.model;

import static javax.persistence.GenerationType.IDENTITY;

import javax.persistence.Cacheable;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Transient;
import javax.validation.constraints.NotNull;
import javax.validation.constraints.Size;

import org.hibernate.annotations.Cache;
import org.hibernate.annotations.CacheConcurrencyStrategy;
import org.hibernate.envers.Audited;
import org.hibernate.validator.constraints.NotBlank;
import org.jboss.pressgang.ccms.model.base.AuditedEntity;

/**
 * BlobConstants generated by hbm2java
 */
@Audited
@Entity
@Cacheable
@Cache(usage = CacheConcurrencyStrategy.TRANSACTIONAL)
@Table(name = "BlobConstants")
public class BlobConstants extends AuditedEntity implements java.io.Serializable {
    private static final long serialVersionUID = 2142789116413087991L;
    public static final String SELECT_ALL_QUERY = "SELECT blobConstants FROM BlobConstants blobConstants";

    private Integer blobConstantsId;
    private String constantName;
    private byte[] constantValue;

    public BlobConstants() {
    }

    public BlobConstants(final String constantName) {
        this.constantName = constantName;
    }

    public BlobConstants(final String constantName, final byte[] constantValue) {
        this.constantName = constantName;
        this.constantValue = constantValue;
    }

    @Id
    @GeneratedValue(strategy = IDENTITY)
    @Column(name = "BlobConstantsID", unique = true, nullable = false)
    public Integer getBlobConstantsId() {
        return blobConstantsId;
    }

    public void setBlobConstantsId(final Integer blobConstantsId) {
        this.blobConstantsId = blobConstantsId;
    }

    @Column(name = "ConstantName", nullable = false, length = 45)
    @NotNull(message = "{blobconstant.name.notBlank}")
    @NotBlank(message = "{blobconstant.name.notBlank}")
    @Size(max = 45)
    public String getConstantName() {
        return constantName;
    }

    public void setConstantName(final String constantName) {
        this.constantName = constantName;
    }

    @Column(name = "ConstantValue", columnDefinition = "longblob")
    public byte[] getConstantValue() {
        return constantValue;
    }

    public void setConstantValue(final byte[] constantValue) {
        this.constantValue = constantValue;
    }

    @Override
    @Transient
    public Integer getId() {
        return blobConstantsId;
    }

}
