/*
  Copyright 2011-2014 Red Hat

  This file is part of PresGang CCMS.

  PresGang CCMS is free software: you can redistribute it and/or modify
  it under the terms of the GNU Lesser General Public License as published by
  the Free Software Foundation, either version 3 of the License, or
  (at your option) any later version.

  PresGang CCMS is distributed in the hope that it will be useful,
  but WITHOUT ANY WARRANTY; without even the implied warranty of
  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
  GNU Lesser General Public License for more details.

  You should have received a copy of the GNU Lesser General Public License
  along with PresGang CCMS.  If not, see <http://www.gnu.org/licenses/>.
*/

package org.jboss.pressgang.ccms.model;

import static javax.persistence.GenerationType.IDENTITY;

import javax.persistence.Cacheable;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Transient;
import javax.persistence.UniqueConstraint;
import javax.validation.constraints.NotNull;
import javax.validation.constraints.Size;

import org.hibernate.annotations.Cache;
import org.hibernate.annotations.CacheConcurrencyStrategy;
import org.hibernate.envers.Audited;
import org.hibernate.validator.constraints.NotBlank;
import org.jboss.pressgang.ccms.model.base.AuditedEntity;

/**
 * FilterOption generated by hbm2java
 */
@Audited
@Entity
@Cacheable
@Cache(usage = CacheConcurrencyStrategy.TRANSACTIONAL)
@Table(name = "FilterOption", uniqueConstraints = @UniqueConstraint(columnNames = {"FilterOptionName", "FilterID"}))
public class FilterOption extends AuditedEntity implements java.io.Serializable {
    private static final long serialVersionUID = 4103450242726344458L;

    private Integer filterOptionId;
    private Filter filter;
    private String filterOptionName;
    private String filterOptionValue;

    public FilterOption() {
    }

    public FilterOption(final Filter filter, final String filterOptionName, final String filterOptionValue) {
        this.filter = filter;
        this.filterOptionName = filterOptionName;
        this.filterOptionValue = filterOptionValue;
    }

    @Id
    @GeneratedValue(strategy = IDENTITY)
    @Column(name = "FilterOptionID", unique = true, nullable = false)
    public Integer getFilterOptionId() {
        return filterOptionId;
    }

    public void setFilterOptionId(Integer filterOptionId) {
        this.filterOptionId = filterOptionId;
    }

    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "FilterID", nullable = false)
    @NotNull
    public Filter getFilter() {
        return filter;
    }

    public void setFilter(final Filter filter) {
        this.filter = filter;
    }

    @Column(name = "FilterOptionName", nullable = false, length = 255)
    @NotNull
    @NotBlank
    @Size(max = 255)
    public String getFilterOptionName() {
        return filterOptionName;
    }

    public void setFilterOptionName(final String filterOptionName) {
        this.filterOptionName = filterOptionName;
    }

    @Column(name = "FilterOptionValue", nullable = false, length = 255)
    @NotNull
    @Size(max = 255)
    public String getFilterOptionValue() {
        return filterOptionValue;
    }

    public void setFilterOptionValue(final String filterOptionValue) {
        this.filterOptionValue = filterOptionValue;
    }

    @Override
    @Transient
    public Integer getId() {
        return filterOptionId;
    }

}
