package org.jboss.pressgang.ccms.model;

import static javax.persistence.GenerationType.IDENTITY;

import javax.persistence.Cacheable;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Transient;
import javax.persistence.UniqueConstraint;
import org.hibernate.validator.NotNull;

import org.hibernate.annotations.Cache;
import org.hibernate.annotations.CacheConcurrencyStrategy;
import org.hibernate.envers.Audited;
import org.jboss.pressgang.ccms.model.base.AuditedEntity;

/**
 * TopicToTag generated by hbm2java
 */
@Entity
@Audited
@Cacheable
@Cache(usage = CacheConcurrencyStrategy.TRANSACTIONAL)
@Table(name = "TopicToTag", uniqueConstraints = @UniqueConstraint(columnNames = {"TopicID", "TagID"}))
public class TopicToTag extends AuditedEntity implements java.io.Serializable {
    private static final long serialVersionUID = -7516063608506037594L;

    private Integer topicToTagId;
    private Topic topic;
    private Tag tag;

    public TopicToTag() {
    }

    public TopicToTag(final Topic topic, final Tag tag) {
        this.topic = topic;
        this.tag = tag;
    }

    @Id
    @GeneratedValue(strategy = IDENTITY)
    @Column(name = "TopicToTagID", unique = true, nullable = false)
    public Integer getTopicToTagId() {
        return topicToTagId;
    }

    public void setTopicToTagId(final Integer topicToTagId) {
        this.topicToTagId = topicToTagId;
    }

    @ManyToOne
    @JoinColumn(name = "TopicID", nullable = false)
    @NotNull
    public Topic getTopic() {
        return topic;
    }

    public void setTopic(final Topic topic) {
        this.topic = topic;
    }

    @ManyToOne
    @JoinColumn(name = "TagID", nullable = false)
    @NotNull
    public Tag getTag() {
        return tag;
    }

    public void setTag(final Tag tag) {
        this.tag = tag;
    }

    @Override
    @Transient
    public Integer getId() {
        return topicToTagId;
    }

}
